import FWCore.ParameterSet.Config as cms

from RecoLocalTracker.SiPixelClusterizer.SiPixelClusterizerPreSplitting_cfi import siPixelClustersPreSplitting
from RecoLocalTracker.SiPixelClusterizer.siPixelRawToClusterCUDA_cfi import siPixelRawToClusterCUDA as _siPixelRawToClusterCUDA
from RecoLocalTracker.SiPixelClusterizer.siPixelFedCablingMapGPUWrapper_cfi import *
from CalibTracker.SiPixelESProducers.siPixelGainCalibrationForHLTGPU_cfi import *

siPixelClustersPreSplittingTask = cms.Task(siPixelClustersPreSplitting)

siPixelClustersCUDAPreSplitting = _siPixelRawToClusterCUDA.clone()
siPixelClustersPreSplittingTaskCUDA = cms.Task(
    siPixelClustersCUDAPreSplitting,
)

from Configuration.ProcessModifiers.gpu_cff import gpu
_siPixelClustersPreSplittingTask_gpu = siPixelClustersPreSplittingTask.copy()
_siPixelClustersPreSplittingTask_gpu.add(siPixelClustersPreSplittingTaskCUDA)
gpu.toReplaceWith(siPixelClustersPreSplittingTask, _siPixelClustersPreSplittingTask_gpu)
